apiVersion: v1
kind: Pod
metadata:
  name: bun-pod-haproxy
spec:
  containers:
    - name: postgres
      image: postgres:bun-1.0
      env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_DB
          value: netflix

    - name: fastify-app
      image: bun:bun-1.0
      env:
        - name: DATABASE_URL
          value: postgresql://admin:secret@localhost:5432/netflix

    - name: haproxy
      image: haproxy:bun-1.0
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
