apiVersion: v1
kind: Pod
metadata:
  name: node-pod
spec:
  containers:
    - name: postgres
      image: postgres:node-1.0
      env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_DB
          value: netflix

    - name: fastify-app
      image: node:node-1.0
      env:
        - name: DATABASE_URL
          value: postgresql://admin:secret@localhost:5432/netflix

    - name: nginx
      image: nginx:node-1.0
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
